# Custom Language File for Launcher Customizer

[ejs.app]
title = "푸르름이 사는 곳"

[ejs.landing]
mediaGitHubURL = "https://github.com/Lunarii1022/Blue"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/Lunarii1022/Blue"
supportLink = "https://github.com/Lunarii1022/Blue/issues"

[ejs.welcome]
welcomeHeader = "푸르름이 사는 곳"
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
